# Generated by Django 5.2.13 on 2026-06-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('pacientes', '0005_remove_paciente_observacoes'),
        ('terapeutas', '0004_especialidades_choices'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agendasemanal',
            unique_together={('paciente', 'terapeuta', 'dia_semana', 'horario')},
        ),
    ]
